export const Constants = {
  TOKEN_KEY: '',
  DOMAIN: '',
  INTEGRATION_API_URL: '',
  IOS_STAGING_CLIENT_ID:
    '',
  IOS_STAGING_CLIENT_SECRET:
    '',

  ANDROID_STAGING_CLIENT_ID:
    '',
  ANDROID_STAGING_CLIENT_SECRET:
    '',
};
